# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

#### 1)  crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na tempreatura global, A NASA disponibiliza dados de diferenças de de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo.

|ano|anomalia termica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.

In [9]:
import pandas as pd
import numpy as np

dados = [1900, 1920, 1940, 1960, 1980, 2000, 2020]
serie = pd.Series(dados)
print(serie)

# Seu código aqui

0    1900
1    1920
2    1940
3    1960
4    1980
5    2000
6    2020
dtype: int64


#### 2) Coloque os anos nos índices conforme a tabela.

In [2]:
indice = [-0.08, -0.27,0.12, -0.03, 0.26 , 0.40, 1.02]
dados = [1900, 1920, 1940, 1960, 1980, 2000, 2020]
serie = pd.Series(dados, index=indice )
print(serie)


-0.08    1900
-0.27    1920
 0.12    1940
-0.03    1960
 0.26    1980
 0.40    2000
 1.02    2020
dtype: int64


#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:

In [3]:
dic_temperaturas = {1900: -.08, 1920: -.27, 1940: .12, 1960: -.03, 1980: .26, 2000: .40, 2020: 1.02}
serie = pd.Series(dic_temperaturas)
# seu código aqui
print(serie)

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64


#### 4) Transforme o ndarray abaixo em um dataframe. 
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.

In [4]:
arr = np.random.normal(100, 10, (20,3))
df = pd.DataFrame(arr)

print(df)
# seu código aqui

             0           1           2
0   104.055553   91.978090  103.266635
1   121.459858  102.562403  118.439342
2    91.741998   97.838026  101.734365
3   106.477079  113.875955   99.505785
4    95.043599   95.246195  109.861160
5    90.310976   89.558201   99.567637
6   112.157961   94.237552   89.544136
7    99.851913   96.188338  119.792503
8   115.257817   92.403384   94.600698
9   114.852236  107.852855  106.339236
10   87.825190  111.449676   98.777501
11   82.588547   94.600798  101.830504
12   91.798225   95.998758  104.101755
13  118.860601   92.683031  108.198177
14  111.762965   87.446265  114.644772
15  105.394987  109.669631  119.607027
16  107.928639   85.084831  104.879988
17   99.520612  118.758460   83.351489
18  103.204300  115.111421   99.240387
19  104.386315  103.680463   99.367935


#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente.

In [5]:
#seu código aqui
ndarray = np.random.normal(100, 10, (20,3))
nomes_colunas = ['x1', 'x2', 'x3']
df = pd.DataFrame(ndarray, index=range(1, 21), columns=nomes_colunas)
np.savetxt('indices.csv', ndarray, delimiter=',')
print(df)


            x1          x2          x3
1   120.653695  109.275655  106.186088
2   107.652385   92.695410  110.395998
3    95.623153   94.532688  101.574689
4   107.098350   87.910116   89.160995
5    90.799942   91.799009   89.002761
6    76.578463  101.272796  100.159999
7   106.335223   87.742455  102.476330
8    95.941038  107.547226  101.929807
9    98.026591   99.288424   92.712488
10   98.802156   87.332483  101.021019
11   96.293763  105.822117   97.334265
12   97.104836   92.190001   90.557931
13   99.902386   92.713256  113.604692
14   91.252853   86.082295   95.855793
15   88.843498   90.309138   98.622038
16   85.082961  103.258069  112.366385
17  103.308835   88.177138   96.428738
18  102.169575   96.244725   87.421136
19   98.632695   84.886038  110.116790
20  114.207379   91.613079  100.725275


#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis).

In [6]:

data = np.loadtxt('indices.csv', delimiter=',')


#calculando a media
media_coluna1 = np.mean(data[:, 0])
media_coluna2 = np.mean(data[:, 1])
media_coluna3 = np.mean(data[:, 2])

#Criando nova coluna com a média
media_colunas = (data[:, 0] + data[:, 1] + data[:, 2]) / 3
nova_coluna = np.reshape(media_colunas, (len(media_colunas), 1))

#Concatenando nova coluna
data_nova_coluna = np.concatenate((data, nova_coluna), axis=1)


#Salvando em csv
np.savetxt('indices_media.csv', data_nova_coluna, delimiter=',')   

print(data_nova_coluna)

[[120.65369498 109.27565459 106.18608776 112.03847911]
 [107.65238492  92.69541049 110.39599841 103.58126461]
 [ 95.623153    94.53268793 101.57468896  97.24350996]
 [107.09834955  87.91011599  89.16099545  94.72315366]
 [ 90.79994239  91.79900945  89.00276092  90.53390425]
 [ 76.57846329 101.27279583 100.15999874  92.67041929]
 [106.33522281  87.74245451 102.47633     98.85133577]
 [ 95.94103793 107.54722584 101.92980667 101.80602348]
 [ 98.02659111  99.28842407  92.71248825  96.67583448]
 [ 98.80215613  87.33248313 101.02101853  95.7185526 ]
 [ 96.29376326 105.82211654  97.33426538  99.81671506]
 [ 97.10483645  92.19000108  90.55793123  93.28425625]
 [ 99.90238582  92.71325609 113.60469165 102.07344452]
 [ 91.25285348  86.08229452  95.85579259  91.06364687]
 [ 88.84349754  90.3091379   98.62203836  92.59155793]
 [ 85.08296076 103.25806886 112.36638479 100.2358048 ]
 [103.30883473  88.17713796  96.42873805  95.97157025]
 [102.16957521  96.24472456  87.42113618  95.27847865]
 [ 98.6326

#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>


In [19]:


# Cálculo da média
media_coluna1 = np.mean(data[:, 0])
media_coluna2 = np.mean(data[:, 1])
media_coluna3 = np.mean(data[:, 2])

# Cálculo do logaritmo natural da média
log_med = np.log((media_coluna1 + media_coluna2 + media_coluna3) / 3)

# Criação da nova coluna "log_med"
#data['log_med'] = log_med

# Imprimindo o DataFrame atualizado
print(data)



[[120.65369498 109.27565459 106.18608776]
 [107.65238492  92.69541049 110.39599841]
 [ 95.623153    94.53268793 101.57468896]
 [107.09834955  87.91011599  89.16099545]
 [ 90.79994239  91.79900945  89.00276092]
 [ 76.57846329 101.27279583 100.15999874]
 [106.33522281  87.74245451 102.47633   ]
 [ 95.94103793 107.54722584 101.92980667]
 [ 98.02659111  99.28842407  92.71248825]
 [ 98.80215613  87.33248313 101.02101853]
 [ 96.29376326 105.82211654  97.33426538]
 [ 97.10483645  92.19000108  90.55793123]
 [ 99.90238582  92.71325609 113.60469165]
 [ 91.25285348  86.08229452  95.85579259]
 [ 88.84349754  90.3091379   98.62203836]
 [ 85.08296076 103.25806886 112.36638479]
 [103.30883473  88.17713796  96.42873805]
 [102.16957521  96.24472456  87.42113618]
 [ 98.63269502  84.88603766 110.11679024]
 [114.20737945  91.61307862 100.72527534]]
